name = "SpectreNG"
version = "0.1.0"
defaultTargets = ["spectreng"]

[[lean_lib]]
name = "SpectreNG"

[[lean_exe]]
name = "spectreng"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

